### ISSUE TITLE
Discarding linear part  of a quadratic Hamiltonian

### ISSUE THREAD

**Issue by FabricioS** [pyphs/pyphs#119]
Dear PyPHSers,
I have some troubles with PyPHS dealing with Hamiltonian such as 
`H = 1/2 * k * (x - x0)**2`
with k some parameter (e.g., a stiffness), x the variable and x0 some offset value.
Calling `obj` the pyphs.Core instance, I got a difference between the gradient and the discrete gradient :
`obj.dxH()` -> k*(x-x0)
`simu.method.dxH()` -> k*(x+dx/2).

It appears to result from the splitting of the linear and nonlinear parts, the numerical method only considers the hessian Q:  H is replaced by 1/2 x^T.Q.x which only retains the quadratic part of the Hamiltonian and discard its linear part (i.e. an constant offset in the gradient).

Is there some easy workaround ?

**Comment by afalaize** [comment]
Hi
No easy workaround: this is a strong issue.
If you can, have a look before I do
Best regards

**Comment by afalaize** [comment]
Hi;
A simple work around would be to make the change of variables \tilde x = x - x0 and propagate it everywhere in the model.
I'll have a look on that asap, but note the future changes will be included in the new repository.
Best regards;
Antoine

**Comment by FabricioS** [comment]
Thanks Antoine,
it is the workaround that we effectively used.
For your information, I was trying to redefine the internal variable as the fluctuation relatively to the equilibrium but in the case when the equilibrium is not at the minimum of the Hamiltonian...
After a glance at the numerical scheme, it seems not that difficult to implement (but I still have to write it down to validate).
thanks again

PS : a "new repository" ? where ?

**Comment by afalaize** [comment]
I mentioned the new repo in issue #47 
https://gitlab.univ-lr.fr/pyphs/pyphs
The reason for moving is abusive non-free usage of the library. Acces will be granted from case to case after a solid licensing model is decided.
Best reagrds

**Comment by afalaize** [comment]
solved by PR #128
