### ISSUE TITLE
minor warnings related to manifest

### ISSUE THREAD

**Issue by gdmcbain** [pyphs/pyphs#124]
To try out the patch suggested for #123, I had to reinstall pyphs from source (previous having merely done `pip install pyphs`).  At the step `python setup.py test`, I received a couple of minor warnings

> warning: no files found matching 'README'
> warning: no files found matching 'LICENSE'

I suspect this will be easy to fix.

**Comment by gdmcbain** [comment]
There are also some more serious warnings (NumPy & SymPy deprecations) and even some errors raised by the test suite, but I'll defer them till after this and #123.

**Comment by afalaize** [comment]
solved by pr #128
