### ISSUE TITLE
Issue when installing PyPHS

### ISSUE THREAD

**Issue by jlochard** [pyphs/pyphs#140]
When running the command "pip install PyPHS", an old release is installed instead of the last one (see Terminal video).

https://user-images.githubusercontent.com/57224810/106269283-9d2d3200-622c-11eb-9dff-c4a2efac5495.mov

**Comment by afalaize** [comment]
Hi
This seems to be an issue related to pip's cache, not pyphs.
How has been pip installed ?
What do you get with a 'pip install --no-cache-dir pyphs'?
Best regards
Antoine

**Comment by afalaize** [comment]
Also I see it complains about missing dependencies. Could you get the requirement file from https://github.com/pyphs/pyphs/blob/master/requirements.txt ans make a 
'pip install -r path/to/requirement.txt'?
Antoine

**Comment by jlochard** [comment]
I installed the requirements and it finally worked ! I probably did the same with a bad requirement.txt which was in the Tutorial folder... Thanks !
