### ISSUE TITLE
'NodeView' object has no attribute 'index'

### ISSUE THREAD

**Issue by lucB18e** [pyphs/pyphs#142]
Hi (sorry for the font and size)
First thank you for all that work. I'm a hobbyist (C++ and juce) coding for fun as I love electric guitar a guitar pickups modeling application (a sort of Roland VG8ex ersatz for those who knows it).
I was VERY interested to play with PyPHS for the electric simulation of magnetic pickups in any configuration.  
I'm on OS X 11.1 Big Sur. I installed Python 3.9.0, using also pyenv to switch to it. I piped PyPHS and tried to run the simplest exemple rlc.
I get an error "'NodeView' object has no attribute 'index'" when I run : python rlc.py (below)
As I'm a complete noob in python, must be a silly mistake I made.
Would you have a clue of what I'm doing wrong ?
 I would greatly appreciate any help.
Regards. Luc
---------------------------
Read netlist rlc.net
from folder /Users/luc/pyphs/pyphs/examples/rlc/
read "electronics.source in ('#', 'n1'): type=voltage;"
read "electronics.resistor R ('n1', 'n2'): R=('R', 1e3);"
read "electronics.inductor L ('n2', 'n3'): L=('L', 0.05);"
read "electronics.capacitor C ('n3', '#'): C=('C', 2e-06)"
Build graph in...
Build graph R...
Build graph L...
Build graph C...
Build graph rlc...
Build core rlc...
Traceback (most recent call last):
  File "/Users/luc/pyphs/pyphs/examples/rlc/rlc.py", line 22, in <module>
    core = netlist.to_core()
  File "/Users/luc/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyphs/graphs/netlists.py", line 223, in to_core
    return graph.to_core(label=label)
  File "/Users/luc/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyphs/graphs/graph.py", line 101, in to_core
    self._build_analysis(verbose=verbose, plot=plot)
  File "/Users/luc/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyphs/graphs/graph.py", line 64, in _build_analysis
    self.analysis = GraphAnalysis(self, verbose=verbose, plot=plot)
  File "/Users/luc/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyphs/graphs/analysis.py", line 43, in __init__
    index_datum = self.nodes.index(datum)
AttributeError: 'NodeView' object has no attribute 'index'

**Comment by WetzelVictor** [comment]
This seems to be linked to a conversion problem maybe? `nodes.index()` indicates the use of `nodes` as a list type.
See a similar error code in:  https://stackoverflow.com/questions/52141158/attributeerror-nodeview-object-has-no-attribute-index

I cannot reproduce the error on my machine (ArchLinux Manjaro, Python 3.9.1). `rlc.py` seems to work.
I ran the unit tests and I get some errors. But they might not be related to this particular issue.

### Error line
File: `pyphs/graphs/analysis.py", line 43, in init`
```(python)
self.nodes = list(graph.nodes())
```
object should be a list indeed.

**Comment by FabricioS** [comment]
The SO question pointed by Victor may in fact help to solve this.
Which version of networkx are you two using?
```python
>>> import networkx
>>> networkx.__version__
```
It seems that upgrade to networkx >=2.0 changed the output object of the `Graph.nodes()` method from a `List` to a `NodeView` (with no `index` method).

I would not necessarily advocate to transform back the NodeView into a list in pyPhs. Graph has a bunch of dedicated method to detect and manipulate edges and nodes.

**Comment by WetzelVictor** [comment]
I am on version 2.5
```(Python)
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx
>>> networkx.__version__
'2.5'
```

**Comment by ghost** [comment]
Hi sorry I was far from home until now....
my networkx is in '2.5' too.  I also checked PyPHS version 0.1.12 here  
After upgrade to last phyps 0.5.1, everything is working now

my first PyPHS install has been done with : pip install pyphs
I think I can close this issue.... Thanks for your fast help....

Best regards. LucB

**Comment by FabricioS** [comment]
Thank you for reporting and properly closing the issue.
Fabrice
