### ISSUE TITLE
AssertionError: flux-controlled edge xBSC1 is effort-controlled I don't understand

### ISSUE THREAD

**Issue by lucB18e** [pyphs/pyphs#143]
Hi, I'm pretty sure it's not a bug but I have a failed attempt I don't understand.

I'm trying to simulate an electric guitar pickups network behavior in all possible configurations with 3 double pickups 
I began with a working netlist (1 double pickup) without the bolded line inspired from your tutorial. in the process part, I set for each sample the 2 voltages sources and get the result through out. it worked, I put the C++ code in a plugin and saw the expected low pass behavior. (very promising after you run the Eigen lib in release mode).

If I try to add the bolded line, I get an error : AssertionError: flux-controlled edge xBSC1 is effort-controlled
I really don't understand what happens with that very simple network. If someone could have a clue or a direction to show me. I would greatly appreciate.

Here is my netlist : 
(a single pickup is simulated with in series a voltage source, a resistor, an inductor and in parallel of all that a capacitor

    _here is the first single pickup_
electronics.source BS ('#', 'BS1'): type='voltage';
electronics.inductor BSL1 ('BS1', 'BS2'): L=('BSL1', 2.2);
electronics.resistor BSR1 ('BS2', 'BSP'): R=('BSR1', 5800.0);
electronics.capacitor BSC1 ('BSP', '#'): C=('BSC1', 120e-12);

    _here is the second single pickup in series withe the first_
electronics.source BN ('BSP', 'BN1'): type='voltage';
electronics.inductor BNL1 ('BN1', 'BN2'): L=('BNL1', 2.2);
electronics.resistor BNR1 ('BN2', 'BNP'): R=('BNR1', 5800.0);
electronics.capacitor BNC1 ('BNP', 'BSP'): C=('BNC1', 120e-12);

electronics.source out ('BNP', '#'): type=current;

electronics.resistor RAMP ('BNP', '#'): R=('RAMP', 1000000.0);

       it works well without this line and I get an error with it
**electronics.capacitor CAMP ('BNP', '#'): C=('CAMP', 500e-12);**

I'm an hobbyist and try to understand PyPhs and use it properly. 
Let me understand if issues like this bores you. I stop immediately these noob questions... 

Best regards
Luc

**Comment by afalaize** [comment]
Hi! 
Thank you for your interest. This error is related with the graph analysis prior to the generation of the core PHS equations.
There is a "criterion"  for the graph to be realizable as  PHS. All the background material is discussed in section 3 of the following reference:
[Antoine Falaize and Thomas Hélie. Passive guaranteed simulation of analog audio circuits: A port-hamiltonian approach. Applied Science, Applied Acoustics, special issue Audio Signal Processing, 2016](
https://hal.archives-ouvertes.fr/hal-01390501/document)
The error you get means that the resulting graph is not realizable. Please, have a look to the reference above (specifically to section 3.2) to have details about what is happening under the hood. If after that you still can not get your application work, do not hesitate to come back here for additional help.
Best regards;
Antoine Falaize

**Comment by ghost** [comment]
Hi
Thank you very much for your time and showing me a direction
I (try to) dive into your reference document
Regards.
LucB
