### ISSUE TITLE
Python 3 compatibility of module fraccalc.py

### ISSUE THREAD

**Issue by TristanLbrn** [pyphs/pyphs#28]
This regards the pyphs module located at `pyphs/dictionary/fraccalc.py`

The function `fractionalIntegratorWeights(p=1, beta=0.5)` runs on python 2.7 and provides
```
([1.749035908843339e-09,
  6.9595144826924863e-08,
  1.8630838378138305e-05,
  2.5524426185241214,
  30.823428129767155,
  359.65116239651917,
  10405809524.289852],
 [0.057174355022894495,
  0.23968633750938143,
  0.14935234505990999,
  5.0600536742396391,
  69.896011597466696,
  999.24983972175335,
  0.96100163823462381])
```
However, on python 3.5, it crashes at the scipy function `minimize`: 
 `MuOpt = minimize(CostFunction, np.ones(NbPoles), bounds=bnds, tol=EPS)` . 
This seems to be related to the argument `bounds`, defined as
`bnds = [(0, None) for n in range(NbPoles)] `.

I found a workaround by defining a constraint instead of the argument` bounds`:
`cons = {'type':'ineq', 'fun': lambda x: x}`
and then calling the minimize function
` MuOpt = minimize(CostFunction, np.ones(NbPoles), constraints=cons, tol=EPS)`.

This yields pretty close results on both python 2.7 and 3.5:
```
([5.2537955919623119e-10,
  8.7617674855431192e-08,
  4.248584273972994e-05,
  2.5524442241508281,
  30.823417010139337,
  359.65123662762471,
  10039015447.979877],
 [0.1903385814114813,
  0.19038402239644209,
  0.065493802706308585,
  5.0600504911897453,
  69.896036812634591,
  999.24963347911387,
  0.99611361809511623])
```

This needs to be checked (and maybe improved) on another plateform (I use Ubuntu 14.04).

_pyphs '0.1.9.7.3'_

**Comment by FabricioS** [comment]
On debian unstable (py3.5.1 shipped), I get the following results with the code in the developpement branch (pulled yesterday), i.e. without changing the 'bounds' argument to 'constraints'.

```
In [4]: from pyphs.dictionary.fraccalc import fractionalIntegratorWeights as fIW

In [6]: fIW(p=1, beta=.5)
Out[6]: 
([5.9222395771425286e-10,
  8.6514873184216438e-08,
  3.291007007428914e-05,
  2.5524445672428118,
  30.823409553802399,
  359.65168749078839,
  9331164281.4163723],
 [0.1688550398838303,
  0.19281084000992138,
  0.084550394329940645,
  5.0600498110328544,
  69.896053720835496,
  999.24838080919255,
  1.0716776276156297])

```

I don't know what the function is expected to do, but is there any case with trusted reference values that could be used to test the function ?

**Comment by afalaize** [comment]
This dictionary (pyphs/dictionary/fraccalc.py) is not currently functional and should not appear in the dictionary. To see the available dictionaries, please do :
>>> from pyphs import dictionary
>>> dir(dictionary)

The reasons are (i) only the fractional intergrators have been tested and (ii) we need to improve the graph analysis to cope with "meta-components", i.e. the realizability of a (single edge) fractional integrator should be analysed before replacing the edge with the actual associated graph.

We will close this issue when (i) the graph analysis is improved to cope with meta components and (ii) that 'fraccalc.py' dictionary is stabilized.

If you want to improve, the basical scientific material can be found in the chapter 7 of [this reference](https://afalaize.github.io/publis/T1.pdf)

**Comment by TristanLbrn** [comment]
@afalaize : Ok for (i) and (ii).

Regarding (ii):
On debian  with Python 3.4.2 I get the following results, that are slightly different from yours @FabricioS  (not surprising since this is an optimization algorithm):

```
fIW(1,0.5)
Out[9]: 
([5.0291239502932468e-10,
  8.3890843631298492e-08,
  5.7523276813605957e-05,
  2.9245373268615986,
  2.5524450441961806,
  30.823377427198938,
  359.65040363007637,
  9555010242.2804394],
 [0.1988417883281024,
  0.1988417883281024,
  0.048372755453822976,
  0.00015871190259670231,
  5.0600488655050331,
  69.896126572125283,
  999.25194787244277,
  1.0465713532938461])

```
...but still, on ubuntu with Python 3.5.2 I get

```
fIW(1,0.5)
Out[9]: 
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
```

**Comment by afalaize** [comment]
#35 implement the fraccalc dictionary and should close this issue. Can you have a look to the examples and confirm?
