### ISSUE TITLE
Implement the use of HDF file format for simulation results

### ISSUE THREAD

**Issue by afalaize** [pyphs/pyphs#45]

**Comment by FabricioS** [comment]
In Moreesc, I used [hdf5pickle](https://pav.iki.fi/software/hdf5pickle) to efficiently serialize the instances of the simulation class (both configuration and results are stored, and the full instance can be reconstructed). It relies on pytables, and has not evolved for a couple of years.
There is also a [hickle](https://github.com/telegraphic/hickle) package that seems newer but more limited than hdf5pickle (only lists and numpy arrays can be stored, only experimental support for py3, but based on h5py).

**Comment by afalaize** [comment]
@FabricioS Waou, thank you. hdf5pickle shall be used for saving python object, and a pytables wrapper shall be used for managing hdf5 results shared with c++ objects.

And, could-we discuss the implementation of the Moreesc objects in the pyphs dictionary? This could be close to the (recent) implementation of the fender rhodes!

**Comment by FabricioS** [comment]
Hi Antoine,
the Moreesc objects are pretty simple. It assumes :
* the input impedance of the acoustic resonator can be expanded on a modal series. In the Laplace domain, it writes $Z(s) = \sum_n C_n/(s_n)$ with the poles $s_n$ and residues $C_n$. The internal variables are then the real and complex parts of the pressure components.
* the dynamics of the mechanic valve can be represented by a transfer function H(s)/P(s) = B(s)/A(s) where $h(s)$ is the valve opening, $p(t)$ the driving pressure, $B(s) and $A(s)$ are two polynomials in the Laplace variable $s$.
* In the case of simple woodwind or brass modelling, the flow is considered as instantaneous, i.e. without intrinsic dynamics.
All the details are in the Acta Acustica paper : https://doi.org/10.3813/AAA.918693

**Comment by FabricioS** [comment]
Hi Antoine,
I just listened to your seminar and "hands on" sessions at Ircam. Thank you for that.
One of the points that were discussed is about the refactoring of the IO subsystem, i.e., the storage of inputs and results of simulations.
How are you doing on that? Would you mind some brainstorming before coding ? I may help if you need

**Comment by afalaize** [comment]
Hi Fabrice,
I opened a topic on the PyPHS Q&A mailing list here:
https://groups.google.com/forum/#!topic/pyphs/2M6-dHJw1EA

**Comment by afalaize** [comment]
PyPHS use HDF files for simulation results since 0.3.
