### ISSUE TITLE
Verbosity affects linear_nonlinear splitting

### ISSUE THREAD

**Issue by FabricioS** [pyphs/pyphs#51]
Commit a11670eda58 introduced verbosity levels, but the condition is wrongly implemented here :
https://github.com/afalaize/pyphs/blob/master/pyphs/numerics/numerical_method/_method.py#L128

```
if self.config['split'] and VERBOSE >= 2:
    print('    Split Linear/Nonlinear...')
    self.linear_nonlinear()
```
should be
```
if self.config['split']:
    if VERBOSE >= 2:
        print('    Split Linear/Nonlinear...')
    self.linear_nonlinear()
```

**Comment by afalaize** [comment]
Quite embarassing... Thank you for pointing it.
This is corrected [here](https://github.com/afalaize/pyphs/commit/bf099ad881812d706308f900572880bf70c707ef).
