### ISSUE TITLE
C++ generation hangs out when a parameter has no numerical value

### ISSUE THREAD

**Issue by FabricioS** [pyphs/pyphs#85]
If a parameter has not been substituted by its numerical value (by using the obj.subs attribute), the C++ generation get stuck in an (infinite ?) loop at the sympy level: see
https://gist.github.com/FabricioS/d7149e3ed294dcc9d0e08c8e5c0c7950

Shall we check for unsubstituted parameters ?

**Comment by afalaize** [comment]
PR #87 should close this issue when merged in master

**Comment by FabricioS** [comment]
Fixed, thanks
