### ISSUE TITLE
Remove special formating of plots for diplay on e.g. retina screens

### ISSUE THREAD

**Issue by afalaize** [pyphs/pyphs#92]
The standard matplotlib display should be used, or at list the special formating should be an option of plot function.

**Comment by FabricioS** [comment]
In fact, even without retina screens, the rendering of the matplotlib figure should rely on the user's configuration, not on the developer's one.
In my case, the preset hard-coded in PyPHS is not visually appealling to me, and I have written my own plotting function that respects my mpl configuration.

**Comment by afalaize** [comment]
This is solved by PR #94 in develop branch
