### ISSUE TITLE
Cannot use greek letter with the LaTeX format

### ISSUE THREAD

**Issue by WetzelVictor** [pyphs/pyphs#96]
I need to use LaTeX character, and I tried to use greek letters for physical values (spring stiffness, damping coefficient) and python returns this error:
```python
  File "/home/victorw/anaconda/envs/pyphs/lib/python3.6/site-packages/sympy/utilities/lambdify.py", line 434, in lambdify
    func = eval(lstr, namespace)

  File "<string>", line 1
    lambda \pi_i,\xi_i,d\pi_i,d\xi_i: ([276.45816*\xi_i, -10.0*\pi_i, -10.0*\pi_i])
                                                                                  ^
SyntaxError: unexpected character after line continuation character
```
Here is a simple code (damped mass-spring system)
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pyphs import Core
import os

# Main system
label = 'issue_test'
core = Core(label)


#%% Adding storage components
# Masse m
pii = core.symbols('\\pi_i')
m = core.symbols('m')
Hm = pii**2/(2.*m)
core.add_storages(pii,Hm)

# Spring
xk, k = core.symbols([ '\\xi_i','k' ])
Hk = k*xk**2/2.
core.add_storages(xk, Hk)


#%% Adding dissipative component
wa, a = core.symbols(['w_a','a'])
za = a * wa
core.add_dissipations(wa, za)

#%% Add connections
core.set_Jxx([[0, -1 ],
              [+1, 0 ]])
core.set_Jxw([ [-1],
               [0]])

core.pprint()

#%% Initializing our system
m_g = 0.1
f0 = 440 #fundamental frequency (Hz)
k_Npm = m_g*(2*3.14157*f0)
kappa_Npm = 5
a_Nspm = 1.

vals = {m:m_g,
        k:k_Npm,
        a: a_Nspm}
core.subs.update(vals)

#%% Simulation
config = {'fs':44100,
          'path':os.path.join(os.getcwd(), label)
         }
T = 1.
nt = int(T*config['fs'])
simu = core.to_simulation(config=config)
```

I'm running PyPHS 0.2.0.1, on anaconda with Python 3.6.4, every dependencies is up-to-date.

**Comment by afalaize** [comment]
Hi;

Thank you for your interest, and, please, note that standard rules of politeness apply here ;)

In short: It is not possible to use latex syntax in python(/sympy). In some cases (e.g. matplotlib plot titles and legends), it is possible to render in math mode "$\pi$". We could build a wrapper in pyphs that would basically escapes every backslashes when necessary, but it is not a priority.

I don't understand why you "need" latex symbols.

If you are looking for fancy printing in python interpreter, you can use [this sympy module](http://docs.sympy.org/0.7.1/modules/galgebra/latex_ex/latex_ex.html), or simply the capabilities of sympy regarding pretty printing of maths:
```
>>> import sympy
>>> sympy.init_printing()  # activate sympy pretty printing
>>> pi = sympy.symbols('pi_1')  # notice there is no backslash
>>> pi   # display nicely most latex symbols
π₁
```

I you want LaTeX commands for symbols in the generated LaTeX files, I suggest that (i) you use standard names for symbols in pyphs (e.g. "pi_i"), and (ii) make a query/replace in the generated LaTeX file to get the proper command (e.g. search "pi_i" => replace by "\pi_i").

Sorry, no solution out of the box, but this a standard python/sympy/pyphs behavior, not an issue. 
I close, and you can open a thread [in the mailing list](https://groups.google.com/forum/#!forum/pyphs) to ask other pyphs users.

**Comment by FabricioS** [comment]
Hi Antoine, Hi Victor,
as mentioned by Antoine, Sympy handles (under the hood) many latex symbols, including greek letters. For instance
`xk, k = core.symbols([ '\\xi_i','k' ])`
can simply be changed to
`xk, k = core.symbols([ 'xi_i','k' ])`
and the xk python variable will be represented by the appropriate $\xi_i$ in the ipython shell, jupyter notebook and the latex report generated by PyPHS.

Best regards

**Comment by WetzelVictor** [comment]
Hi Antoine, Hi Fabrice

Thank you for your answers! You solved my problems :)

**Comment by afalaize** [comment]
Hi!
@FabricioS The rendering of symbols in the latex report generated by PyPHS is controlled in the `symbol_names` function (line 14 in [pyphs/pyphs/misc/latex/tools.py](https://github.com/pyphs/pyphs/blob/master/pyphs/misc/latex/tools.py)):

```
def symbol_names(core):
    sn = {}
    for var in [r'x', 'dx', r'w', r'u', r'y', r'cy', r'p', r'o', r'g', r'z_symbols']:
        for symb in geteval(core, var):
            string = str(symb)
            lab = string[1:]
            sn.update({symb: string[0]+r'_{\mathrm{'+lab+r'}}'})
    for symb in core.subs.keys():
        string = str(symb)
        lab = string[1:]
        sn.update({symb: string[0]+r'_{\mathrm{'+lab+r'}}'})
return sn

```
In short, the (nowhere written) rule is: the first character of the symbol's string is the variable, the remaining part is the variable label: the symbol "xstiff" will be rendered as $x_{\mathrm{stiff}}$.

@WetzelVictor you can redesign the function `symbol_names` to your needs, and submit it as a pull request if you think it's worth it.

I admit we could do a lot regarding the rendering of PyPHS structures, but again this is not a priority.

All the best;

Antoine
